apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-admin-logback-xml
data:
  logback-spring.xml: |+
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration debug="true">
    	<springProperty scope="context" name="appName" source="spring.application.name"/>
    	<property name="LOG_ROOT" value="/app/logs" />
    	<property name="PROJECT_NAME" value="aibank"/>
    	<appender name="STDOUT"
    		class="ch.qos.logback.core.ConsoleAppender">
    		<encoder>
    			<pattern><![CDATA[%date{HH:mm:ss.SSS} [T:%X{traceId:-} S:%X{spanId:-}] [%X{trackingid}] [%thread] %-5level %logger{15} %msg\n]]></pattern>
    		</encoder>
    	</appender>
    	<appender name="ADM_LOG_APPENDER"
    		class="ch.qos.logback.core.rolling.RollingFileAppender">
    		<file>${LOG_ROOT}/admin/admin-${POD_NAME}.log</file>
    		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
    			<fileNamePattern>${LOG_ROOT}/archives/admin/admin-${POD_NAME}-%d{yyyy-MM-dd}.log.gz</fileNamePattern>
    			<!-- backup for 3 months -->
    			<maxHistory>90</maxHistory>
    		</rollingPolicy>
    		<encoder class="net.logstash.logback.encoder.LogstashEncoder">
    			<fieldNames>
    				<timestamp>@timestamp</timestamp>
    				<stackTrace>exception</stackTrace>
            <includeMdcKeyName>traceId</includeMdcKeyName>
            <includeMdcKeyName>spanId</includeMdcKeyName>
            <includeMdcKeyName>sessionid</includeMdcKeyName>
            <includeMdcKeyName>channelid</includeMdcKeyName>
            <includeMdcKeyName>trackingid</includeMdcKeyName>
            <includeMdcKeyName>clientip</includeMdcKeyName>
            <includeMdcKeyName>deviceid</includeMdcKeyName>
            <includeMdcKeyName>custid</includeMdcKeyName>
            <includeMdcKeyName>springinstanceid</includeMdcKeyName>
            <includeMdcKeyName>pageid</includeMdcKeyName>
            <includeMdcKeyName>locale</includeMdcKeyName>
            <includeMdcKeyName>userid</includeMdcKeyName>
            <includeMdcKeyName>httpMethod</includeMdcKeyName>
            <includeMdcKeyName>requestURI</includeMdcKeyName>
            <includeMdcKeyName>httpStatus</includeMdcKeyName>
    			</fieldNames>
    			<customFields>{"podName":"${POD_NAME}", "project.name":"${PROJECT_NAME}", "project.application.name":"${appName}","project.country":"tw","project.logtype":"admin","tags":["public","admin","SIT"]}</customFields>
    		</encoder>
    	</appender>
    	<logger name="org.apache.http" level="INFO" additivity="false">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</logger>
    	<logger name="org.springframework" level="INFO" additivity="false">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</logger>
    	<logger name="com.ibm.tw" level="DEBUG" additivity="false">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</logger>
    	<logger name="com.tfb" level="DEBUG" additivity="false">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</logger>
    	<logger name="springfox" level="INFO" additivity="false">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</logger>
    	<logger name="io.lettuce" level="INFO" additivity="false">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</logger>
    	<logger name="io.netty" level="INFO" additivity="false">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</logger>
    	<logger name="PERFORMANCE_LOGGER" level="DEBUG" additivity="false">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</logger>
    	<logger
    		name="org.springframework.jdbc.core.StatementCreatorUtils"
    		level="TRACE" additivity="false">
    		<appender-ref ref="STDOUT" />
    	</logger>
    	<logger name="org.springframework.jdbc.core.JdbcTemplate"
    		level="TRACE" additivity="false">
    		<appender-ref ref="STDOUT" />
    	</logger>
    	<logger name="net.ttddyy"
    		level="INFO" additivity="false">
    		<appender-ref ref="STDOUT" />
    	</logger>
    
    	<root level="DEBUG">
    		<appender-ref ref="STDOUT" />
    		<appender-ref ref="ADM_LOG_APPENDER" />
    	</root>
    </configuration>
