apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-oauth-server
spec:
  rules:
  - host: oauth.tpebnknanot.cldatu1.groupt.fbt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-oauth-server
            port:
              number: 9999

