apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-swagger-gateway
spec:
  rules:
  - host: swagger.tpebnknanot.cldatu1.groupt.fbt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-swagger-gateway
            port:
              number: 8080

