apiVersion: v1
kind: Service
metadata:
  name: svc-swagger-gateway
spec:
  selector:
    app: swagger-gateway
  ports:
    - name: oauth-http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
