apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-admin-frontend
spec:
  rules:
  - host: b2e.tpebnknanot.cldatu1.groupt.fbt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-admin-frontend
            port:
              number: 8080
      - path: /pagecode
        pathType: Prefix
        backend:
          service:
            name: svc-admin-chl
            port:
              number: 8080

