apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-ixtein
spec:
  rules:
  - host: ixtein.tpebnknanot.cldatu1.groupt.fbt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-nginx
            port:
              number: 8080
      - path: /ixtein
        pathType: Prefix
        backend:
          service:
            name: svc-ixtein
            port:
              number: 9080
      - path: /ixtein/directupdate/download
        pathType: Prefix
        backend:
          service:
            name: svc-nginx
            port:
              number: 8080

