apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-ixtein-admin
spec:
  rules:
  - host: ixteinadm.tpebnknanot.cldatu1.groupt.fbt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-ixtein-admin
            port:
              number: 9090
      - path: /v2/receive
        pathType: Prefix
        backend:
          service:
            name: svc-ixtein-push
            port:
              number: 8080
